version: "3.9"

services:
  db:
    image: mysql
    env_file: .env
    ports:
      - 33061:3306
  geth:
    image: ethereum/client-go
    volumes:
      - type: bind
        source: ~/ethereum
        target: /root
    command: --syncmode light --http --ws --http.api personal,eth,net,web3 --http.corsdomain '*' --http.addr 0.0.0.0 --ws.addr 0.0.0.0
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303